### PR TITLE
Options window not getting closed on home button press solution

### PR DESCRIPTION
**Pull request by panwarab**
Solved  it using a broadcast receiver to intercept home button press

### CODE REVIEW

**Comment by panwarab** [comment]
@piyush0  Please review the PR

**Comment by piyush0** [comment]
Getting an error on pressing home button after shortening using the window. Kindly fix. 
Pull again and send a new PR. It is a good practice to squash the commits if you have more than 1. 👍

**Comment by panwarab** [comment]
@piyush0 Will share it by tomorrow. :)

**Comment by panwarab** [comment]
Closing this. Opening a new one with squashed commits.

**Pull request closed without merging**
