### PR TITLE
Material Design addition to widget

### PR DESCRIPTION
**Pull request by panwarab**
This PR references #1 and #11. Please have a look. There are upstream merge conflicts, I guess. Is there a way to resolve it at your end?
.Here are the screenshots.:-

shrtlr1

shtlr2

### CODE REVIEW

**Comment by panwarab** [comment]
@piyush0  please have a look.

**Comment by piyush0** [comment]
@AbhirojPanwar Palette Code is not working well on any of my emulators. Will find improvements later. Going with previous changes as of now.

**Comment by panwarab** [comment]
@piyush0 I missed the testing on the emulator, only tested it on my device. May I ask what's the exact problem so that I can work on it?

**Comment by piyush0** [comment]
I'll check on other devices and see if this works properly. This is definitely a better change but need to be 100% sure before making changes.

**Comment by panwarab** [comment]
agreed. Please let me know of that.

**Pull request merged**
